name: lens_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  shelf_router:
  shelf:
  mysql_client:
  uuid:
  shelf_web_socket:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
